### ISSUE TITLE
Enhancement for TANs

### ISSUE THREAD

**Issue by marcuslelle** [pdir/contao-survey#44]
## Description

"Nice to have"
Consider alphanumeric TANs instead of only six digits.

"Must have"
Would it be possible to add the TAN to the user's link (as a GET parameter) and automatically enter the TAN in the form on start.
That would be very comfortable for users.

**Comment by cmette** [comment]
Alphanumeric TANs: This should not be a problem, but must be put on hold since this function is already implemented. I have to check first to what extent the existing code can be used further.

The second feature "must have" is also already implemented in the original code. However, I am still in the process of expanding the feature.
